//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwsFileSyncStatus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AwsFileSyncStatus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
        ///	&lt;xsl:output method=&quot;html&quot;/&gt;
        ///	&lt;xsl:param name=&quot;archiveId&quot;&gt;BcJ4_XfTO6Rs9qcxJl84IEsXYfKlX6J5XwaUdGQwjqnzDdRP58hsnE1pivZsQz_TU4R11YyTujfIuz1Iqe6ALST99_vNSDs2aZHIMgovWNPISR6x0IP_FNQpR-Cx2DnYk1WxL5HZog&lt;/xsl:param&gt;
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///		&lt;xsl:apply-templates select=&quot;//ArchiveList/Archive[ArchiveId=$archiveId]&quot;/&gt;
        ///	&lt;/xsl:template&gt;
        ///	&lt;xsl:template match=&quot;Archive&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;ti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ArchiveDetails {
            get {
                return ResourceManager.GetString("ArchiveDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
        ///	&lt;xsl:output method=&quot;html&quot;/&gt;
        ///  &lt;xsl:param name=&quot;exception&quot; /&gt;
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///	&lt;html&gt;
        ///		&lt;head&gt;
        ///			&lt;title&gt;AWS File Sync&lt;/title&gt;
        ///			&lt;meta http-equiv=&apos;refresh&apos; content=&apos;10&apos; /&gt;
        ///		&lt;/head&gt;
        ///		&lt;body&gt;
        ///			&lt;h1&gt;AWS File Sync&lt;/h1&gt;
        ///      &lt;xsl:if test=&apos;string-length($exception) &gt; 0&apos;&gt;
        ///        &lt;h2 style=&apos;color:red&apos;&gt;Exception Occurred&lt;/h2&gt;
        ///        &lt;h3 style=&apos;color:red&apos;&gt;
        ///          &lt;x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
        ///	&lt;xsl:output method=&quot;html&quot;/&gt;
        ///	&lt;xsl:param name=&quot;vaultName&quot;&gt;Family_Pictures&lt;/xsl:param&gt;
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///		&lt;xsl:apply-templates select=&quot;/VaultSync/Vaults/Vault[VaultName=$vaultName]&quot;/&gt;
        ///	&lt;/xsl:template&gt;
        ///	&lt;xsl:template match=&quot;Vault&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;AWS Vault Details&lt;/title&gt;
        ///    &lt;style&gt;
        ///      a.button {
        ///      display:inline;
        ///      color: darkblue;
        ///      font-fam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VaultDetails {
            get {
                return ResourceManager.GetString("VaultDetails", resourceCulture);
            }
        }
    }
}
